package common

const (
	GET_COMPLETED_RUNS_BY_WFID = "GET_COMPLETED_RUNS_BY_WFID"
	GET_WF_RUN_BY_RUNID        = "GET_WF_RUN_BY_RUNID"
	RUN_WF_BY_WFID             = "RUN_WF_BY_WFID"
	RERUN_WF_BY_RUNID          = "RERUN_WF_BY_RUNID"
	GET_WF_RUNS_SINCE          = "GET_WF_RUNS_SINCE"
	GET_JOBS_BY_RUNID          = "GET_JOBS_BY_RUNID"
	GET_JOB_LOG_BY_JOBID       = "GET_JOB_LOG_BY_JOBID"
	GET_ALL_JOBS_LOG           = "GET_ALL_JOBS_LOG"
	TRIGGER_WORKFLOW_BY_WFID   = "TRIGGER_WORKFLOW_BY_WFID"
	RERUN_WORKFLOW_BY_RUNID    = "RERUN_WORKFLOW_BY_RUNID"
	GET_RUN_LOGS_BY_RUNID      = "GET_RUN_LOGS_BY_RUNID"
	GET_JOBS_STATUS_BY_RUN     = "GET_JOBS_STATUS_BY_RUN"
	RUN_COMPLETE_WORKFLOW      = "RUN_COMPLETE_WORKFLOW"
)
